### ISSUE TITLE
Add howto to configure with Pi-hole

### ISSUE THREAD

**Issue by ced-mos** [DigitaleGesellschaft/DNS-Resolver#18]
In order to protect the whole network at home a guide how to configure a Pi-hole with the DigitaleGesellschaft DNS would be cool.

**Comment by schnellschnell** [comment]
There is an arcticle in c't in german:

https://www.heise.de/select/ct/2019/5/1551091804941410

**Comment by ced-mos** [comment]
Too late xD. Added my approach in the PR https://github.com/DigitaleGesellschaft/DNS-Resolver/pull/19 .

What do you think?

**Comment by schnellschnell** [comment]
> Too late xD. Added my approach in the PR https://github.com/DigitaleGesellschaft/DNS-Resolver/pull/19 .
> 
> 
> 
> What do you think? 

I've just installed pi-hole via docker. Will look into your solution. 

There's a description in the official doc: https://docs.pi-hole.net/guides/dns-over-https/

**Comment by ced-mos** [comment]
> There's a description in the official doc for non docker: https://docs.pi-hole.net/guides/dns-over-https/

I've already seen this doc but thought, a docker solution would also be nice. 

Were you able to test it?

**Comment by schnellschnell** [comment]
Finally I tested it. It works fine but it's not up to date (anymore). How do you keep it up to date?

**Comment by ced-mos** [comment]
@ryru @schnellschnell Sorry for the late answer. Indeed the updating is a problem. 

Currently the upstream images have been only updated once in the last year which is not enough. In addition I just tried to build the docker images by myself based on the used Dockerfiles but those do not work anymore as the links are not correct anymore. Therefore, my guide which is build on [testdasi repo](https://github.com/testdasi/pihole-base-buster-plus/) is not future proof.

That's why I currently use an [adguard home docker container](https://hub.docker.com/r/adguard/adguardhome) as DNS as the software already provides all the dependencies for DOT and DOH where only the DNS address of the DigitaleGesellschaft needs to be added.

As the pi-hole is still a nice application I will check in the next month if I find a good solution which does not take to much maintenance effort. Otherwise I would close the PR as I don't have the time to spend more time on it.

**Comment by ryru** [comment]
I close this one. Please reopen if you need any further support or information. Thx!
