### ISSUE TITLE
Resolvers not reachable

### ISSUE THREAD

**Issue by Migsi** [DigitaleGesellschaft/DNS-Resolver#21]
I've been continuously trying (over a few months) to use your public DNS service, but I am unable to reach it neither from my network nor from services like https://dnslookup.online/. If the service wasn't abandoned, what could be the issue? Is the service geolocked somehow?

**Comment by ryru** [comment]
The servers are reachable over DNS over HTTPS (DoH) port 443/tcp or DNS over TLS (DoT) port 853/tcp but not over unencrypted DNS on port 53/udp. How/where did you try to configure our DNS resolvers?

We provide some basic client [configuration how-tos](https://github.com/DigitaleGesellschaft/DNS-Resolver#browser-configuration) maybe they can help you?

**Comment by Migsi** [comment]
> The servers are reachable over DNS over HTTPS (DoH) port 443/tcp or DNS over TLS (DoT) port 853/tcp but not over unencrypted DNS on port 53/udp. How/where did you try to configure our DNS resolvers?
> 
> We provide some basic client [configuration how-tos](https://github.com/DigitaleGesellschaft/DNS-Resolver#browser-configuration) maybe they can help you?

It was indeed my fault. I didn't notice the given IP adresses just referred to the DoT/DoH services. When did you stop providing unencrypted DNS? I understand the security implications, but it would be convenient for devices which still don't allow the usage of DoT/DoH.

**Comment by ryru** [comment]
We, Digital Society Switzerland, never provided DNS over unencrypted 53/udp. A summary about our service can be found here: https://www.digitale-gesellschaft.ch/dns/ (German only). Hope this helps you.
