### ISSUE TITLE
Not a bug, just a question for FritzBox DoT settings

### ISSUE THREAD

**Issue by katastrophe92** [DigitaleGesellschaft/DNS-Resolver#25]
Hello DigitaleGesellschaft
Do I need to Set `Use other DNSv6 servers` and `Use other DNSv4 servers` also or just `DNS over TLS (DoT)` without the option`Allow fallback to non-encrypted name resolution in the internet`
Thank you for offering this DNS 🥇

**Comment by muuvmuuv** [comment]
> Allow fallback to non-encrypted name resolution in the internet

Dependes on what your need is. If you have not enough fallback DoT's you would end up with no website being loaded in case of all DNS fail. This ensures it fallback to your provider/fritz resolution.

**Comment by ryru** [comment]
@katastrophe92 any open questions here?

**Comment by ryru** [comment]
Maybe this link is helpful to you: https://www.heise.de/ratgeber/Schneller-und-ohne-Sperren-Alternative-DNS-Server-einsetzen-8659971.html

I'll close this issue for now.
