### ISSUE TITLE
DNS servers are not reachable

### ISSUE THREAD

**Issue by KizunaH** [DigitaleGesellschaft/DNS-Resolver#7]
Digital Society Switzerland

Mentioned plain text DNS servers are not reachable.
https://github.com/DigitaleGesellschaft/DNS-Resolver#technical-information--configuration-how-tos

@ryru @4-FLOSS-Free-Libre-Open-Source-Software

**Comment by ryru** [comment]
Hey @KizunaH we do not mention nor offer unencrypted DNS services. You can use our services only over DoT oder DoH.

**Comment by KizunaH** [comment]
@ryru sorry. i didnt get it.
how a user able to get benefit from provided IP addresses? i couldn't use them as bootstrap for DOT or DOH neither `tls://185.95.218.42`

**Comment by ryru** [comment]
Usually you do not have to use ip addresses to configure DoT or DoH, the domain names are sufficient. The ip addresses are only relevant if you want to do more [advanced](https://github.com/DigitaleGesellschaft/DNS-Resolver/blob/master/howtos/browser/firefox-DE.md#experten) configurations or if you have a restrictive firewall setup and want to allow connections only to our servers on port 853. This means the ip addresses are mentioned more for information reasons.

Currently not all operating systems and browsers have similar DoT or DoH support. So maybe your preferred software does not have good and easy to use DoT or DoH configuration options at the moment. Firefox and Android are examples for well supported platforms. Please have a look at our [How-To section](https://github.com/DigitaleGesellschaft/DNS-Resolver/tree/master/howtos) (unfortunately in German only at the moment).

Hope this helps you!

**Comment by KizunaH** [comment]
Got it.
